apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-k8s
  namespace: spark-operator
spec:
  type: Python
  mode: cluster
  image: "riccelso/spark-k8s-test:3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/spark-test.py"
  sparkVersion: "3.1.1"
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    # serviceAccount: default
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
