apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: default
  labels:
    app: mongodb-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-internal
  template:
    metadata:
      labels:
        app: mongodb-internal
    spec:
      containers:
      - name: mongodb-internal
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-password
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  namespace: default
spec:
  selector:
    app: mongodb-internal
  ports:
  - port: 27017
    targetPort: 27017
